### ISSUE TITLE
[Minor] Gold star on Feral Cat information is unclear

### ISSUE THREAD

**Issue by RaphaelKyle** [info442-sp21/j-team#10]
I noticed that there's a gold star next under the feral cat. I'm not quite sure what its purpose is of being there. To me, it feels like I can click on it and "mark it as my favorite animal", but it does not give me feedback that it marked it as my Favorite. Also, maybe have a label for the star so that the users know that its behavior is marking it as a favorite and that it'll be in their favorites list. (I did not know the star did something originally until exploring the app). 

Environment: Chrome Version 91.0.4472.77 (Official Build) (x86_64), macOS Big Sur (11.4)

Steps to reproduce: Clicking on learn about this animal redirects you to the Feral Cat information page. 

Expected result: Clicking on the star tells me that it did something, which is marking it as my favorite, and that it can be found on the Favorites section (the list-icon). 
Actual result: Clicking on the star does not tell me anything.

**Comment by gidchia** [comment]
That's a great idea! We'll work to improve the Favorite's page in due time.
