### ISSUE TITLE
Clicking on home causes a a flashing "sign up" and "welcome [Minor]

### ISSUE THREAD

**Issue by diegot-stack** [info442-sp21/j-team#11]
![Screen Shot 2021-05-25 at 2 01 22 PM](https://user-images.githubusercontent.com/56012534/119568289-2f1ff400-bd62-11eb-9362-4a049447e916.png)
![Screen Shot 2021-05-25 at 2 01 38 PM](https://user-images.githubusercontent.com/56012534/119568301-33e4a800-bd62-11eb-9655-17771d6542ff.png)

When switching between the pages there is a small flashing of the sign up option before it says welcome again. 

Steps to recreate: 
1. Log in 
2. Click in between the profile page and another page 

Environment: Desktop, Chrome (Version 90.0.4430.212) on macOS Mojave

**Comment by kristina-te** [comment]
User also doesn't have to click between different pages and the profile page to do get this bug. Even clicking on the profile page over to re-render causes this flashing.

**Comment by gidchia** [comment]
We will be working to fix this bug. Thank you!

**Comment by gidchia** [comment]
Having spoken with my engineer, we've established that this might be an issue with Firebase. We do not intend to further investigate and resolve the issue.
