### ISSUE TITLE
[Major] Post submissions does not post

### ISSUE THREAD

**Issue by RaphaelKyle** [info442-sp21/j-team#12]
I tried submitting a test photo of Pikachu (not an animal, really) with a caption, and I don't see it on the website. Is this feature not implemented yet, or is the post "under approval"? I would have feedback on the behavior that occurred for this. If the post feature isn't implemented yet, I would have feedback on something like, "This post is sent to be under review". If it does work, I would give feedback that it was posted and tell the user where to expect their submission to be found (top/bottom of the home page?). 

Environment: Chrome Version 91.0.4472.77 (Official Build) (x86_64), macOS Big Sur (11.4)

Steps to reproduce: 
1. Click on the camera icon 
2. Upload an image with a title and caption

Actual result: It says post successfully, but I don't see it anywhere on the site. 
Expected result: Either the post is "under review" or tell me where to find the post.

**Comment by gidchia** [comment]
Issue could not be reproduced

**Comment by gidchia** [comment]
Animal Identification is under our team's stretch goals, and will not be implemented. The posting issue could not be reproduced.

**Comment by cherimarie** [comment]
Raphael- the new posts show up at the bottom of the feed, not top. It surprised me, too, when my new post wasn't visible, but when I scrolled I found it. It's possible that yours was created successfully, but just wasn't visible.
