### ISSUE TITLE
[Minor] I can post nothing

### ISSUE THREAD

**Issue by RaphaelKyle** [info442-sp21/j-team#13]
I noticed there are no checkpoints on the user that deters them from posting nothing (no picture, no title, no caption). 

Environment: Chrome Version 91.0.4472.77 (Official Build) (x86_64), macOS Big Sur (11.4) 

Steps to reproduce: 
1. Click on the camera icon at the bottom 
2. Click submit 

Expected result: It shouldn't let me by telling me the post failed. 
Actual result: It tells me the post was successful.

**Comment by gidchia** [comment]
Thank you for your suggestion. We will take this into consideration for future versions of our mobile application.

**Comment by gidchia** [comment]
Duplicate: https://github.com/info442-sp21/j-team/issues/5
