### ISSUE TITLE
Changing Pages Does Not Change Navigation Bar Location Indicator [minor]

### ISSUE THREAD

**Issue by smckissick1** [info442-sp21/j-team#14]
Minor

The navigation bar at the bottom of the page does not change as the user navigates to other pages, it stays dark on the upload page despite the user's location.

Encountered in Chrome 90.0.4430.212 on MacOS Big Sur

1. Log in (does not matter which method)
2. Click "Go to main page"
3. Click 1st, 3rd, or 4th buttons on Nav Bar

Actual Result: Shading of icons does not change despite user's location
Expected Result: Shading of icon matches the page the user is currently on

**Comment by gidchia** [comment]
Thank you for your suggestion. We will take this into consideration for future versions of our mobile application.
