### ISSUE TITLE
[Minor] Can successfully submit an empty post, but it does not show up on homepage

### ISSUE THREAD

**Issue by ashshah1** [info442-sp21/j-team#15]
Upon submitting empty fields, I see a success message that says that the post was submitted but I'm not able to see it on the home page. 

Expected behavior
- Some form of form validation that prevents empty fields from being submitted
- But, if accepted, posts should then show up on the home page

**Comment by gidchia** [comment]
We will be working to fix this bug. Thank you!

**Comment by cherimarie** [comment]
I think this should be categorized as a minor bug. It seems like correct behavior that empty posts do not display on home feed, but there should be validation on submission so that empty posts cannot be created.

**Comment by changz23-1836696** [comment]
Hi, we have fixed this bug in commit "fix upload". Users are only allowed to upload a post with at least an image selected. If the user does not want to include species or texts in the post, a default species and caption will take place on the post card.
