### ISSUE TITLE
New Feature Request: Add Sign Up

### ISSUE THREAD

**Issue by jordanjones243** [info442-sp21/j-team#16]
On the sign up page, there is only an option to sign in, which assumes the user already has an account. When a user does not have an account, there is no place to create one. Adding a separate feature would be useful when new users come to access the site, so they can create their own profile, username, picture and such.

**Comment by gidchia** [comment]
What device/browser were you using when this bug occurred?

**Comment by cherimarie** [comment]
This is a major bug.

**Comment by changz23-1836696** [comment]
This bug is fixed in commit "fix log in"
