### ISSUE TITLE
Add location to each post

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/j-team#17]
**Describe the bug**
Users don't know where the animal was spotted 

**To Reproduce**
1. Go to https://info442juju.web.app/home
2. Scroll to a post

**Expected behavior**
Expected to see a location (e.g. city name, street name, etc) on where the animal was spotted

**Screenshots**
![image](https://user-images.githubusercontent.com/41980535/119570693-52986e00-bd65-11eb-8181-13af7c860740.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge

**Comment by gidchia** [comment]
That's a great idea! We'll work to improve the landing page in due time.
