### ISSUE TITLE
[Minor] can't see my post

### ISSUE THREAD

**Issue by mequanentshiferaw** [info442-sp21/j-team#19]
I  submitted a post with a photo with a little description, I wasn't able to see my post or delete it.  Is this feature was implemented under the profile page, but it doesn't work. since there a profile page you guys should add user posts to edit or delete the post.

**Comment by gidchia** [comment]
What device/browser were you using when this bug occurred?

**Comment by changz23-1836696** [comment]
Hi, the login page is for users to view their current login status and is not designed to be a profile page where users can edit or delete posts. Since we do not hear back from you about the device/browser information to reproduce this bug, we will label it as invalid and close the issue.
