### ISSUE TITLE
[Major] Missing title after submitting an event

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/j-team#23]
** Describe bug**
Title reads 'Modal title' after submitting an event

**To reproduce**
1. Go to https://demeter-uw.web.app/create
2. Enter event details 
3. Create event 

**Expected behavior**
Expected to see a confirmation title (e.g. 'Your event is created')

**Screenshots**
![image](https://user-images.githubusercontent.com/41980535/119572757-1d414f80-bd68-11eb-8235-913e59471e7c.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge

**Comment by gidchia** [comment]
This issue was submitted for the wrong project.
