### ISSUE TITLE
[Major] The post form does not validate what user upload

### ISSUE THREAD

**Issue by tichx** [info442-sp21/j-team#24]
**Describe the bug**
On the make a post form, the upload feature does not validate whether the user uploads an image or not. I can upload a pdf or whatever format, which is very dangerous. Malicious users could upload virus to the server.

**Severity**
Major

**To Reproduce**
1. Login
2. Go to the Posting page
3. Create a post
4. upload a random file (like a pdf, or python file)

**Expected behavior**
Any other format than images should be rejected with an alert.

**Current behavior**
It accepts all the files users upload and shows upload successfully.

**Screenshots**
<img width="842" alt="WX20210525-145701@2x" src="https://user-images.githubusercontent.com/12144060/119573761-8ecdcd80-bd69-11eb-860a-a7847f44014e.png">
<img width="1672" alt="WX20210525-145636@2x" src="https://user-images.githubusercontent.com/12144060/119573769-91c8be00-bd69-11eb-8af4-0c47e71aa6ef.png">

**Desktop :**
* Device: Macbook Pro 2018
* OS: MacOS Big Sur
* Browser: Chrome
* Version: Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by gidchia** [comment]
Thank you for calling out the bug. We will work on this to provide the proper error handling.

**Comment by changz23-1836696** [comment]
Hi, we have fixed this bug in commit "fix issue #24". The file uploader now will only accept image files, and the submit button will not be activated before the user has at least one image file uploaded.

**Comment by cherimarie** [comment]
I would consider this a minor bug.
