### ISSUE TITLE
Consider moving nav bar to top of page

### ISSUE THREAD

**Issue by embascom** [info442-sp21/j-team#25]
I did not notice the nav bar at the bottom for almost a minute and was confused as to how to navigate the pages. I think for a desktop app, it makes more sense to have the nav bar at the top of the page and potentially put labels with the icons.

**Comment by drishtividyarthi** [comment]
I think it could also be useful to center the nav bar and make it a little bigger. It could be helpful to also add a text description next to the icons to make it even more clear.

**Comment by changz23-1836696** [comment]
Hi, our app is designed to work on mobile devices so we to the navbar at the bottom of the page to imitate the mobile app layout. We will not make any changes on the navbar in this version, but we can make the app change the layout for different devices if we have more time in the future.
