### ISSUE TITLE
New feature request: Landing or About Page

### ISSUE THREAD

**Issue by abq14** [info442-sp21/j-team#26]
Include information about the site and why the user should sign up for an account. Right now, the first page the user sees on the site is an option to sign up, but the user may not want to sign up if they don't know what the site does. Adding a landing page with some reasons to sign up may help convince the user to sign up.

**Comment by gidchia** [comment]
That's a great idea! We'll work to improve the landing page in due time.

**Comment by gidchia** [comment]
Duplicate: https://github.com/info442-sp21/j-team/issues/18

**Comment by gidchia** [comment]
Duplicate: https://github.com/info442-sp21/j-team/issues/18
