### ISSUE TITLE
Enhancement: Explanation of Eye Witness Reports

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/j-team#27]
I think it could be useful to add an explanation under the ability to see eye witness reports to explain to the user what exactly that feature is doing and what they can learn from it. 

I think this feature was a little confusing for me because clicking the post allows you to see the animals and then also the eye witness reports so it might good to consolidate these two things on one page and have explanations under each section. This would not only make it easier for the user to understand the information they are saying but also navigate between the pages.

**Comment by gidchia** [comment]
That's a great idea! We'll work to improve the eye-witness news page in due time.

**Comment by gidchia** [comment]
fixed.
