### ISSUE TITLE
Enhancement, Navbar

### ISSUE THREAD

**Issue by brendantran** [info442-sp21/j-team#28]
I think you guys should maximize the screen space for the navbar on larger screens and add text to the icons. This way, it'll be easier to find out what the icons represent.

**Comment by gidchia** [comment]
We'll probably not add text to our tabs on the navbar, just because it does create a conflict with our design language. As for sizing, the app is designed for iphoneX sized devices.

**Comment by gidchia** [comment]
Duplicate: https://github.com/info442-sp21/j-team/issues/3
