### ISSUE TITLE
enhancement: favorites page

### ISSUE THREAD

**Issue by brendantran** [info442-sp21/j-team#29]
On the favorites tab, I think it'd be helpful to have some feedback when there are no current favorites so that the user knows that the page works. The feedback could say something like "You have no favorites, click the star to add."

**Comment by gidchia** [comment]
That's a great idea! We'll work to improve the favortie's page in due time.

**Comment by gidchia** [comment]
Thank you for your suggestion. We will take this into consideration for future versions of our mobile application.
