### ISSUE TITLE
Enhancement: Splash Page

### ISSUE THREAD

**Issue by popi1141** [info442-sp21/j-team#30]
The app itself is great, but what would help improve first time usage is having a splash page and/or custom login page as the first thing users see when entering the website vs the bare login screen it has right now. 

![image](https://user-images.githubusercontent.com/45519338/119576531-81592780-bdeb-11eb-9402-5a68d7ef5219.png)

![image](https://user-images.githubusercontent.com/45519338/119576554-8a49f900-bdeb-11eb-8b6d-2418bc6ba97c.png)

**Comment by gidchia** [comment]
That's a great idea! We'll work to improve the landing page in due time.

**Comment by gidchia** [comment]
Duplicate: https://github.com/info442-sp21/j-team/issues/18
