### ISSUE TITLE
Minor: Profile Flashes as Sign Up Page Instead of the Log Out Area When Initially Selected

### ISSUE THREAD

**Issue by popi1141** [info442-sp21/j-team#31]
1. Log In to the App
2. Go to the Profile Section
3. For a Split Second, the Screen Shows as the Sign Up Page -- even if you're currently logged in.

Not exactly a major issue, but it does kind of break the UI.

![image](https://user-images.githubusercontent.com/45519338/119576777-fa587f00-bdeb-11eb-9b0a-79d309ce5ded.png)

**Comment by gidchia** [comment]
We noticed this bug too. However, this is not significant and we will not be focusing on the bug fix for the next version. Thank you for your input!

**Comment by gidchia** [comment]
Duplicate: https://github.com/info442-sp21/j-team/issues/11
