### ISSUE TITLE
Enhancement: Post layout more adapted to desktop users

### ISSUE THREAD

**Issue by ifrahm** [info442-sp21/j-team#33]
Currently the home screen displays all the posts in a column. This works best when the user is on a phone because they could scroll. A suggestion would be that if the user is on a desktop to change the layout of the posts so they are spread across the screen or appear larger to take up the white space.

**Comment by gidchia** [comment]
We will take this enhancement into consideration. At the moment, the team is focused on a mobile version of the application and will be focusing on other enhancements.
