### ISSUE TITLE
Nav bar not appearing immediately after logging in

### ISSUE THREAD

**Issue by embascom** [info442-sp21/j-team#34]
- minor
- right after the user logs in, the profile the user is brought to does not include the navbar, but when you return to the profile after going to the main page, it does appear.
- Chrome v90.0.4430.85 on Windows 10
- Steps to Reproduce = open application, and then sign in 
- actual result = No navbar at the bottom of the page
- expected result = the navbar appearing at the bottom of the page

![image](https://user-images.githubusercontent.com/49084428/119594518-cbf98600-bd90-11eb-8a08-d0a7127abe88.png)

**Comment by gidchia** [comment]
We will be working to fix this bug. Thank you!

**Comment by changz23-1836696** [comment]
Got this bug fix in commit "fix issue #34". Thank you!
