### ISSUE TITLE
Enhancement - Understand when favorite button has been selected

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/j-team#4]
Feature request: When clicking on the star (favorite button) on a specific post or feature, it would be super informative and helpful to be able to see somehow that the favorite button was actually clicked on besides going to the favorite page. For example, the star could be not colored in when unselected and then when clicked on to favorite, the star could be colored in.

**Comment by gidchia** [comment]
Thank you for your suggestion. We will take this into consideration for future versions of our mobile application.
