### ISSUE TITLE
Upload is successful without an image or post information [minor]

### ISSUE THREAD

**Issue by yejukim** [info442-sp21/j-team#5]
The upload has a successful page without uploading an image or post information.

Steps to reproduce: 
1. Click Create a Post
2. Do not input any information into the text box and/or uploaded image
3. Click Submit 

Expected: Failed upload page without any information filled
Actual: Successful upload page 

Environment: Chrome 90.0.4430.93 on macOS (Mojave)

**Comment by gidchia** [comment]
We will be working to fix this bug. Thank you!

**Comment by changz23-1836696** [comment]
Hi, we have fixed this bug in commit "fix upload". The user will not be allowed to upload without an image selected.
