### ISSUE TITLE
[Major] Unable to add an user-posted species to favorite

### ISSUE THREAD

**Issue by tichx** [info442-sp21/j-team#6]
**Describe the bug**
After I posted my wildlife animal, I could not click into the post and add that species as my favorite.

**Severity**
Major

**To Reproduce**
1. Login
2. Go to the posting tab
3. Create a post
4. Go back to the posting page
5. Find the posted animal, and click on it
6. it does not show add to my favorite button

**Expected behavior**
Show the add to the favorite button.

**Current behavior**
Shows the "there is no information on that species"

**Screenshots**
<img width="1098" alt="WX20210525-135408@2x" src="https://user-images.githubusercontent.com/12144060/119567690-79ed3c00-bd61-11eb-81c8-be2b32d1ffed.png">

**Desktop (please complete the following information):**
* Device: MacBook Pro (15-inch, 2018)
* OS: Mac OS Big Sur 11.3.1
* Browser: Chrome
* Version: Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by gidchia** [comment]
We will be working to fix this bug. Thank you!

**Comment by changz23-1836696** [comment]
Hi, we got this bug fixed at commit "fix issue #6". For animals that dose not included in our information server, we will give users a button to check on Wikipedia and a button to add this species to users' favorite list.
