### ISSUE TITLE
Being able to click and expand images of a species on the species info page

### ISSUE THREAD

**Issue by dorilusions** [info442-sp21/j-team#8]
Currently, you can see images of a species at the bottom of the species info page (see attached image).  However, you cannot click and take a closer look at them.

![image](https://user-images.githubusercontent.com/43550545/119567864-ad2fcb00-bd61-11eb-87c5-61b03db80234.png)

This would be nice, as the existing images are small and hard to see.

**Comment by gidchia** [comment]
Thank you for your suggestion. We will take this into consideration for future versions of our mobile application.
