### ISSUE TITLE
Enhancement: Make the first page the user sees the newsfeed instead of the profile page. 

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/j-team#9]
It might be a nicer user flow to have the app after the user logs in, be the newsfeed of different animals rather than being the profile page. So once the user logs in, it could direct them to that page instead of the profile page first and then having the user select "Go to main page!"

I think this might be useful because the user flow would be smoother and it would capture the user's attention more easily. The user is more likely to stay engaged with the app if they are able to learn and see relevant content faster.

**Comment by gidchia** [comment]
Thank you for your suggestion. We will take this into consideration for future versions of our mobile application.
